### ISSUE TITLE
AutoSDF checkpoint of text2shape

### ISSUE THREAD

**Issue by peterjohnsonhuang** [yccyenchicheng/SDFusion#14]
Hi, 
Appreciate your great work! I notice that you compare the text-guided generation results with AutoSDF. Can you provide your checkpoint of AutoSDF on the text2shape dataset? It seems that AutoSDF only provide checkpoint on a different text-guided dataset (ShapeGlot?). Thank you!

**Comment by yccyenchicheng** [comment]
Hi,

We train SDFusion on ShapeGlot to compare with AutoSDF. We do not have the AutoSDF checkpoint on text2shape at this moment. Sorry.

**Comment by peterjohnsonhuang** [comment]
I see, thank you for the reply!
