### ISSUE TITLE
Questions about get more geometric details

### ISSUE THREAD

**Issue by yuanzhen2020** [yccyenchicheng/SDFusion#15]
Hi, @yccyenchicheng.
Appreciate your great work! I want to get more geometric details of the generated ShapeNet models. One direct way is to increase the resolution of the SDF to 128, but this requires more memory and computational resources. To reduce memory consumption, it may be necessary to reduce the dimensionality of the latent space. However, I am not sure if reducing the dimensionality of the latent space can result in a good VQVAE model? Do you have any suggestions on this? Or are there other ways to get more geometric details of the generated model?

**Comment by yccyenchicheng** [comment]
Yes, there is a trade-off between the dimensions of the latent space and the reconstruction quality.

Reducing the memory usage while improving the quality is the major challenger to scale up the model.
