### ISSUE TITLE
Cannot import name 'sdf_to_pcd' from 'utils.util_3d'

### ISSUE THREAD

**Issue by anna-debug** [yccyenchicheng/SDFusion#16]
Hi, I ran into this issue when trying out the notebook for unconditional generation and shape completion. It seems that there is no "sdf_to_pcd" function in util_3d.py.

**Comment by yccyenchicheng** [comment]
Hi,

They are not required and you can safely commend them out. We will update the code accordingly. Thanks

**Comment by yccyenchicheng** [comment]
fix now! please check again, thanks
