### ISSUE TITLE
Code Problems

### ISSUE THREAD

**Issue by xmu-xiaoma666** [yccyenchicheng/SDFusion#2]
Thanks for your great. I would like to know when the code will be released?

**Comment by 618QRC** [comment]
Same question.

**Comment by pratos** [comment]
Here for the code release

**Comment by yccyenchicheng** [comment]
The code will be released soon! Stay tuned.

**Comment by swsongwei** [comment]
Sit && wait

**Comment by kakou34** [comment]
Any updates about code release date?

**Comment by yccyenchicheng** [comment]
Sorry for the wait. We plan to release the code within the following weeks. Thanks!
