### ISSUE TITLE
Missing file ./launchers/launch_create_sdf_shapenet.sh 

### ISSUE THREAD

**Issue by abhinanda-punnakkal** [yccyenchicheng/SDFusion#22]
Hi @yccyenchicheng , 

Thank you for releasing the code for this very interesting work.   
While trying to follow the README.md, I see that the file for preparing the data, `./launchers/launch_create_sdf_shapenet.sh ` is unavailable.

Could you please upload this? 

Thanks 
Abhinanda

**Comment by Cartahall** [comment]
Hello @yccyenchicheng,

I'm also trying to replicate the training of SDFusion, but the missing *create_sdf files make this quite hard

Best
Aurel

**Comment by Bathsheba** [comment]
I too would like this, I want to attempt training SDFusion on a dataset of scupture.

**Comment by yccyenchicheng** [comment]
Hello,

It is located here: https://github.com/yccyenchicheng/SDFusion/blob/master/preprocess/launchers/launch_create_sdf_shapenet.sh

You first need to change to the directory `preprocess` to run the preprocessing script:

```
cd preprocess
./launchers/launch_create_sdf_shapenet.sh 
```

Thank you.
