### ISSUE TITLE
Missing model vqvae-snet-all.pth

### ISSUE THREAD

**Issue by RaresAmbrus** [yccyenchicheng/SDFusion#3]
Thank you for your work and for open-sourcing the code! I am trying to run the demo_txt2shape notebook, but it seems like it's missing the model for `vqvae-snet-all.pth`. Did I miss something? Thanks for the help!

**Comment by yccyenchicheng** [comment]
Hi @RaresAmbrus,

Thanks for pointing this out. Here is the link to the vqvae checkpoint: https://uofi.box.com/shared/static/zdb9pm9wmxaupzclc7m8gzluj20ja0b6.pth.

Download and save it to `saved_ckpt/vqvae-snet-all.pth` and it should work.

**Comment by RaresAmbrus** [comment]
Great, thanks a lot for the quick response!
