### ISSUE TITLE
Missing file bpe_simple_vocab_16e6.txt.gz

### ISSUE THREAD

**Issue by anticdimi** [yccyenchicheng/SDFusion#33]
Hi, 
While trying to run `demo_img2shape.ipynb` I encountered the following error, in the cell nr 3 (creating the model):
```
FileNotFoundError: [Errno 2] No such file or directory: 'random_path/SDFusion/external/clip/bpe_simple_vocab_16e6.txt.gz'
```
Any help with this one?
Thanks!

**Comment by ShijieZhao36** [comment]
I also face that problem. How do you solve it?



> Hi, While trying to run `demo_img2shape.ipynb` I encountered the following error, in the cell nr 3 (creating the model):
> 
> ```
> FileNotFoundError: [Errno 2] No such file or directory: 'random_path/SDFusion/external/clip/bpe_simple_vocab_16e6.txt.gz'
> ```
> 
> Any help with this one? Thanks!

**Comment by gogojjh** [comment]
> Hi, While trying to run `demo_img2shape.ipynb` I encountered the following error, in the cell nr 3 (creating the model):
> 
> ```
> FileNotFoundError: [Errno 2] No such file or directory: 'random_path/SDFusion/external/clip/bpe_simple_vocab_16e6.txt.gz'
> ```
> 
> Any help with this one? Thanks!

Hi, did you address this issue?
