### ISSUE TITLE
Error in installation

### ISSUE THREAD

**Issue by sumantha-NTS** [yccyenchicheng/SDFusion#4]
Hi,
I am trying to install dependency packages for SDFusion, but getting an error in the pytorch3D installation.

I am using cuda 11.7 and nvidia driver 515.
What environment did you use for inference? like cuda, nvidia-driver version etc.

**Comment by swsongwei** [comment]
@sumantha-NTS 
I follow the settings from author @yccyenchicheng 
![image](https://user-images.githubusercontent.com/44295578/226597509-53c008ec-4bd5-4b77-af96-dc62f2c92901.png)
for pytorch3d:
i install it by command: pip install "git+https://github.com/facebookresearch/pytorch3d.git" from [https://github.com/facebookresearch/pytorch3d/blob/main/INSTALL.md](url).
So, you may need to notice use other command to install whcih may change your the version of pytroch.

**Comment by sumantha-NTS** [comment]
Thank you. 
I have installed pytorch and pytorch3d through pip, it worked for me.
`pip install torch==1.9.1+cu111 torchvision==0.10.1+cu111 torchaudio==0.9.1 -f https://download.pytorch.org/whl/torch_stable.html`
`pip install "git+https://github.com/facebookresearch/pytorch3d.git"`
