### ISSUE TITLE
about text-to-shape synthesis

### ISSUE THREAD

**Issue by peterjohnsonhuang** [yccyenchicheng/SDFusion#5]
Hi, 
Thank you for this great work! I have a question about the training process of text-to-shape. According to your paper, the model is trained to generate only the geometry of objects, so how do you handle the color/texture-related texts in the text-to-shape dataset? Did you just let the conditioned diffusion model learns to ignore such information and just capture the geometry-related information? Or did you apply other preprocess to eliminate color-related words in a given text?

**Comment by yccyenchicheng** [comment]
Hi,

Yes! Currently we ignore such information and do not apply some filtering for the text datasets.

**Comment by peterjohnsonhuang** [comment]
Got it! Thank you for the reply!

**Comment by yccyenchicheng** [comment]
I think we have tried some phrase. The results will mainly depend on the 2D diffusion model.

**Comment by peterjohnsonhuang** [comment]
I see, so that means the generated texture might not align with the data distribution ( e.g., in terms of FID or IS) of the texture of text2shape dataset but still somehow reasonable, right? Hope I didn't misunderstand your reply 😂

**Comment by yccyenchicheng** [comment]
yes the distribution of textures in text2shape might not align with stable diffusion

**Comment by peterjohnsonhuang** [comment]
Thanks!
