### ISSUE TITLE
Computational resource.

### ISSUE THREAD

**Issue by swsongwei** [yccyenchicheng/SDFusion#6]
What your work need which GPU and how much time for training?

**Comment by yccyenchicheng** [comment]
we use V100 or A6000 to train our model. The memory usage are 32 GB or 48 GB per GPU. Training time varies by stages. VQVAE on all catetogries take around 7~10 days on one GPU. Diffusion model takes longer (also 7~14 days) and I don't quite remember, sorry!

We provide tensorboard to visualize the training progress.

**Comment by RyanHTR** [comment]
> we use V100 or A6000 to train our model. The memory usage are 32 GB or 48 GB per GPU. Training time varies by stages. VQVAE on all catetogries take around 7~10 days on one GPU. Diffusion model takes longer (also 7~14 days) and I don't quite remember, sorry!
> 
> We provide tensorboard to visualize the training progress.

Do you mean it takes 7~14 days to train the model with one V100 GPU? Thanks.

**Comment by yccyenchicheng** [comment]
I update my comment. tilde becomes strike through in my original comment. Sorry for the confusion!
