### ISSUE TITLE
NOT Provide launch_create_sdf_snet.sh

### ISSUE THREAD

**Issue by yjcaimeow** [yccyenchicheng/SDFusion#7]
HI @yccyenchicheng ,

I didn't find the file "launch_create_sdf_snet.sh". Could you please to share it?

Bests, 
Yingjie

**Comment by yccyenchicheng** [comment]
Hi it is a typo. The .sh file should be `launch_create_sdf_shapenet.sh`.

I have fixed the readme. Thanks!

**Comment by yjcaimeow** [comment]
But there is not any file named as "*_create_sdf_*.sh"?

**Comment by yccyenchicheng** [comment]
Yes there is not. It calls `create_sdf.py` but not `create_sdf.sh`
