### ISSUE TITLE
About Multiple Modalities

### ISSUE THREAD

**Issue by yjcaimeow** [yccyenchicheng/SDFusion#8]
Hi @yccyenchicheng ,

I have some question about multi-modalities.  Which dataset is this portion of the function implemented on? and When the code for this part will be release ?

Best regards,
Yingjie CAI

**Comment by yccyenchicheng** [comment]
The dataset for image-shape is from [3d-r2n2](https://github.com/chrischoy/3D-R2N2). The text-shape is from [text2shape](http://text2shape.stanford.edu/).

This part along with the training of buildingnet and texturization will be released soon!

**Comment by yjcaimeow** [comment]
Thank you for your patient reply.

So text2shape dataset can support text and partial shape two condition info at the same time?

Best,
Yingjie

**Comment by yccyenchicheng** [comment]
Shape completion is achieved naturally when training the diffusion model. The paired data we train is: (img and/or text, shape), where the and/or is achieved by dropout during training. In the inference, we can given partial shape to guide the shape generation process, while using classifier-free guidance to control the strength from image or text conditions.

**Comment by yjcaimeow** [comment]
Thans a lot!
